apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-service
  template:
    metadata:
      labels:
        app: coffee-service
    spec:
      containers:
      - name: coffee-service
        image: rebelthor/sleep
        env:  # Environment variables will be updated by the operator
          - name: ROAST_LEVEL  # Replace with actual env var names if different
            value: dark
