# permissions for end users to view coffees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: waiter-operator
    app.kubernetes.io/managed-by: kustomize
  name: coffee-viewer-role
rules:
- apiGroups:
  - divebar.ghcr.io
  resources:
  - coffees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - divebar.ghcr.io
  resources:
  - coffees/status
  verbs:
  - get
