apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: memcached-operator
  name: memcached-operator-memcached-editor-role
rules:
- apiGroups:
  - cache.ttl.sh
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.ttl.sh
  resources:
  - memcacheds/status
  verbs:
  - get
