---
# tasks file for Coffee
- name: start the bar
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-bar'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: bar
        template:
          metadata:
            labels:
              app: bar
          spec:
            containers:
            - name: bar
              image: "ttl.sh/joriswebsitetest"
              imagePullPolicy: Always
              ports:
                - containerPort: 5000
              env:
              # Define the environment variable
              - name: DRINKS
                valueFrom:
                  configMapKeyRef:
                    # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                    name: '{{ ansible_operator_meta.name }}-bar'
                    # Specify the key associated with the value
                    key: drinks
- name: Create configmap using server side apply
  kubernetes.core.k8s:
    namespace: '{{ ansible_operator_meta.namespace }}'
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ ansible_operator_meta.name }}-bar'
      data:
        drinks: |
            {{ drinks | to_json }}
    server_side_apply:
      field_manager: ansible
  notify:
    - restart deployment
- name: Expose Flask port with ClusterIP
  kubernetes.core.k8s_service:
    state: present
    name: '{{ ansible_operator_meta.name }}-bar'
    namespace: '{{ ansible_operator_meta.namespace }}'
    ports:
    - port: 5000
      protocol: TCP
    selector:
      app: bar