---
# tasks file for Coffee
- name: start the bar
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-bar'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: bar
        template:
          metadata:
            labels:
              app: bar
          spec:
            containers:
            - name: bar
              # command:
              # - sleep
              # - infinity
              image: "ttl.sh/joriswebsitetest"
              ports:
                - containerPort: 5000
              env:
              - name: NUMBER_OF_DRINKS
                value: "{{ coffee.amount }}"
- name: Expose Flask port with ClusterIP
  kubernetes.core.k8s_service:
    state: present
    name: '{{ ansible_operator_meta.name }}-bar'
    namespace: '{{ ansible_operator_meta.namespace }}'
    ports:
    - port: 5000
      protocol: TCP
    selector:
      app: bar