apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: your-image-name:tag
        env:
        - name: MY_ENV_VAR
          value: "my_value"
        - name: ANOTHER_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: my-secret-key